# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Quotely' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Quotely
  pod 'SwiftLint'
  pod 'lottie-ios'
  pod 'Kingfisher'
  pod 'JGProgressHUD'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'FirebaseCrashlytics'
  pod 'UITextView+Placeholder'
  pod 'IQKeyboardManagerSwift'
  pod 'FirebaseFirestoreSwift', '8.1.0-beta'

end
